apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-a-deployment
  labels:
    app: microservice-a 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice-a 
  template:
    metadata:
      labels:
        app: microservice-a
    spec:
      containers:
      - name: microservice-a
        image: local/microservices-a:0.0.1
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m
          limits:
            cpu: 500m
        env:
        - name: MYSQL_DATABASE 
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: db-host
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-username
        - name: MYSQL_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password 

---

apiVersion: v1
kind: Service
metadata:
  name: microservice-a-service
spec:
  selector:
    app: microservice-a
  # type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8181
      targetPort: 80 
      # nodePort: 30002