apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: microservice-a-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: microservice-a-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10