apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: microservice-b-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: microservice-b-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10