apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: wordpress-app
spec:
  ports:
    - port : 80
  selector:
    app: wordpress-app
    tier: frontend
  type: LoadBalancer
  